# Generated by Django 4.2.10 on 2024-03-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_created_product_data_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='data_start',
            field=models.DateTimeField(),
        ),
    ]
