# Generated by Django 4.2.10 on 2024-03-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_data_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='max_students_in_group',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
